// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7DIHWbh87STaaNHx4q_nhqxGzOBj8K9c',
    appId: '1:645813014301:web:b3aa4a5b18280f89b65bf4',
    messagingSenderId: '645813014301',
    projectId: 'flutterproject-8e5d7',
    authDomain: 'flutterproject-8e5d7.firebaseapp.com',
    storageBucket: 'flutterproject-8e5d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAcSvyy3YOwV4QYUXd1fLeeGTH-fuK964',
    appId: '1:645813014301:android:927dfbd32780e4b1b65bf4',
    messagingSenderId: '645813014301',
    projectId: 'flutterproject-8e5d7',
    storageBucket: 'flutterproject-8e5d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDD88Q8fpE7kqiHGXwni-3puc5mb1NY0',
    appId: '1:645813014301:ios:be51c51dbeda4593b65bf4',
    messagingSenderId: '645813014301',
    projectId: 'flutterproject-8e5d7',
    storageBucket: 'flutterproject-8e5d7.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnDD88Q8fpE7kqiHGXwni-3puc5mb1NY0',
    appId: '1:645813014301:ios:f2d6659a7c805924b65bf4',
    messagingSenderId: '645813014301',
    projectId: 'flutterproject-8e5d7',
    storageBucket: 'flutterproject-8e5d7.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
